---
- hosts: all
  become: True
  tasks:
    - name: update /etc/hosts with a proper fqdn. vagrant sucks at doing this
      template: src=etc_hosts.j2 dest=/etc/hosts

    - name: update the /etc/hostname file
      hostname: name="{{ ansible_hostname }}.vagrant.vm"

    - name: |
        make sure softwre-properties-common is installed.
        it adds the add-apt-repository command, which is used by the next task
      apt: name=software-properties-common

    - name: add saltstack ppa
      apt_repository:
        repo:  "ppa:saltstack/salt"
        update_cache: yes

    - name: install saltstack minion
      apt: name=salt-minion
      notify: restart salt minion

    - name: add the ppa that includes the latest version of reclass 1.4+
      apt_repository: repo=ppa:anonymouz/reclass

    - name: install reclass
      apt: name=reclass

    - name: create directory where reclass config is stored
      file: path=/etc/reclass state=directory

    - name: add custom changes to reclass config in /etc/reclass
      copy: src=reclass-config.yml dest=/etc/reclass/reclass-config.yml

  handlers:
    - name: restart salt minion
      service: name=salt-minion state=restarted



