---
- hosts: all
  become: True
  tasks:
    - name: update /etc/hosts with a proper fqdn. vagrant sucks at doing this
      template: src=etc_hosts.j2 dest=/etc/hosts

    - name: update the /etc/hostname file
      hostname: name="{{ ansible_hostname }}.vagrant.vm"

    - name: |
        make sure softwre-properties-common is installed.
        it adds the add-apt-repository command, which is used by the next task
      apt: name=software-properties-common

    - name: add saltstack ppa
      apt_repository:
        repo:  "ppa:saltstack/salt"
        update_cache: yes

    - name: install saltstack minion
      apt: name=salt-minion
      notify: restart salt

  handlers:
    - name: restart salt
      service: name=salt-minion state=restarted



