---
- hosts: all
  become: True
  tasks:
    - name: install the saltmaster
      apt: name=salt-master
      notify: restart salt master

    - name: install reclass
      apt: name=reclass

    - name: install git
      apt: name=git

    - name: create directory where reclass config is stored
      file: path=/etc/reclass state=directory

    - name: add custom changes to reclass
      copy: src=reclass-config.yml dest=/etc/reclass/reclass-config.yml

    - name: add custom changes to the salt master config
      copy: src=master.conf dest=/etc/salt/master.d/master.conf
      notify: restart salt master

  handlers:
    - name: restart salt master
      service: name=salt-master state=restarted
