---
- hosts: all
  become: True
  vars:
    base_sls_path: /srv/salt/env/prd
    salt_formula_path: /usr/share/salt-formulas/env
    reclass_git_repo: https://github.com/linuxsimba/mk20-lab-salt-model.git
    reclass_git_repo_install_dir: /srv/salt/reclass
    base_salt_formulas:
        - { name: 'salt', gitpath: "https://github.com/tcpcloud/salt-formula-salt" }
        - { name: 'git', gitpath: "https://github.com/tcpcloud/salt-formula-git" }
        - { name: 'linux', gitpath: "https://github.com/linuxsimba/salt-formula-linux" }
        - { name: 'ntp', gitpath: "https://github.com/tcpcloud/salt-formula-ntp" }
        - { name: 'reclass', gitpath: "https://github.com/tcpcloud/salt-formula-reclass" }


  tasks:
    - name: install the saltmaster
      apt: name=salt-master
      notify: restart salt master

    - name: install git
      apt: name=git

    - name: create directory where reclass config is stored
      file: path=/etc/reclass state=directory

    - name: add the ppa that includes the latest version of reclass 1.4+
      apt_repository: repo=ppa:anonymouz/reclass

    - name: install reclass
      apt: name=reclass

    - name: create directory where reclass config is stored
      file: path=/etc/reclass state=directory

    - name: add custom changes to reclass config in /etc/reclass
      copy: src=reclass-config.yml dest=/etc/reclass/reclass-config.yml

    - name: add reclass config for openstack-salt from github
      git:
        repo: "{{ reclass_git_repo }}"
        dest: "{{ reclass_git_repo_install_dir }}"

    - name: add custom changes to the salt master config
      template: src=master.conf.j2 dest=/etc/salt/master.d/master.conf
      notify: restart salt master

    - name: |
        create salt formula path.
      file: path="{{ salt_formula_path }}" state=directory

    - name: |
        create path for prd salt states to use. dir is /srv/salt/env/prd
      file: path="{{base_sls_path}}" state=directory

    - name: install base salt formulas.
      git:
        repo: "{{item.gitpath}}"
        dest: "{{salt_formula_path}}/{{ item.name}}"
      with_items: "{{base_salt_formulas}}"

    - name: link salt formulas into the prd state directory
      file:
        src: "{{ salt_formula_path}}/{{ item.name}}/{{item.name}}"
        dest: "{{base_sls_path}}/{{item.name}}"
        state: link
      with_items: "{{ base_salt_formulas}}"

    - name: |
        create the /srv/salt/classes/service directory.
        in the reclass files one defines "service.git.client", what reclass does
        is look in /srv/salt/reclass/classes/service/git for the client.sls file.
      file:
        path: "{{ reclass_git_repo_install_dir}}/classes/service"
        state: directory

    - name: |
       symlink the services folder to a folder in the /srv/salt/reclass/classes/services folder.
       without this, reclass fails to work. add the metadata from the salt formulas to the
       /srv/salt/reclass/classes/services folder so that reclass class statements like "service.git.client" work.
      file:
        src: "{{salt_formula_path}}/{{item.name}}/metadata/service"
        dest: "{{ reclass_git_repo_install_dir}}/classes/service/{{item.name}}"
        state: link
      with_items: "{{base_salt_formulas}}"

  handlers:
    - name: restart salt master
      service: name=salt-master state=restarted
